server:
  port: 80

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: microservicecloud-dept-client

eureka:
  client:
#    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept80-client
    prefer-ip-address: true
	
	#中文
  #空格
	#缩进